### ISSUE TITLE
Adding support to set minimum api level 19, save to gallery feature

### ISSUE THREAD

**Issue by idzdigital** [natsuite/NatCorder-Performance-Extensions#10]
This asset does great job of recording videos on android device as expected. I have two question regarding this.
-How do I make my captured videos be visible in android photo gallery?
-Minimum API level needed by this plugin is 24+ so it is not letting me create build with minimum API level set to 19 in android player settings (I have many users with api below 24). Is it possible to set plugin minimum api to 19 and not allow to record video for device with api less than 24?
Thanks

**Comment by olokobayusuf** [comment]
Hey there @idzdigital , I have inline responses below:

> How do I make my captured videos be visible in android photo gallery?

[NatShare!](https://docs.natsuite.io/natcorder/integrations/social-sharing).

> Minimum API level needed by this plugin is 24+ so it is not letting me create build with minimum API level set to 19 in android player settings (I have many users with api below 24). Is it possible to set plugin minimum api to 19 and not allow to record video for device with api less than 24?

This isn't possible, because the library itself defines the Android minimum. Also, it relies on recent API's so even if you could get it to build, you would likely encounter runtime errors.

**Comment by circleslee** [comment]
> This asset does great job of recording videos on android device as expected. I have two question regarding this.
> -How do I make my captured videos be visible in android photo gallery?
> -Minimum API level needed by this plugin is 24+ so it is not letting me create build with minimum API level set to 19 in android player settings (I have many users with api below 24). Is it possible to set plugin minimum api to 19 and not allow to record video for device with api less than 24?
> Thanks
AndroidMainfest.xml setting
<uses-sdk tools:overrideLibrary="xxx.xxx.xxx"/> is useful
