### ISSUE TITLE
Error adding package

### ISSUE THREAD

**Issue by Rutherfordum** [natsuite/NatCorder-Performance-Extensions#12]
Hi, I can't add a package to my project

Cannot perform upm operation: Unable to add package [https://github.com/natsuite/NatCorder-ARFoundation-Integration.git]:
  [https://github.com/natsuite/NatCorder-ARFoundation-Integration.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by olokobayusuf** [comment]
You seem to be using the wrong link, `https://github.com/natsuite/NatCorder-ARFoundation-Integration.git`. See the [setup instructions](https://github.com/natsuite/NatCorder-Performance-Extensions).
