### ISSUE TITLE
When Zoom sharing is on App miss behave due to Mic access. 

### ISSUE THREAD

**Issue by ti-hardikshah** [natsuite/NatCorder-Performance-Extensions#14]
Hello everyone. I got a strange issue. In my application, I am using natcoder for record screens targeting iOS devices. 
I had used a video player in scene and record button for screen recording, normally it's working as expected but when I try to call on zoom with someone and try to share my screen and open my application then I am getting mic-related error and app not working as expected.

**Comment by olokobayusuf** [comment]
As we discussed on Discord, it seems like this happens because Zoom gets exclusive access to the microphone.
