### ISSUE TITLE
NatCorder Unity error

### ISSUE THREAD

**Issue by unobatbayar** [natsuite/NatCorder-Performance-Extensions#15]
Hello @olokobayusuf 

Thank you for making NatCorder.

It might not be related to this repository but in `Unity 2021.2.4f`, NatCorder gives the following error:

`NativeCameraDevice.cs(154,17): error CS0165: Use of unassigned local variable 'handle'`

We can comment out to solve this error or initialise the handle.

![Screenshot 2021-11-30 at 10 38 52](https://user-images.githubusercontent.com/38866249/144389026-da9c8139-b079-42c3-828a-ce449d4d800a.png)

But, is this a good solution? What should we do?

I highly value your reply.

**Comment by olokobayusuf** [comment]
Hey there @unobatbayar , thanks for opening this. It is a known issue in NatDevice, and there's a fix in the [1.2.0 update that's in beta right now](https://docs.natml.ai/natdevice/insiders/changelog#1.2.0-under-development). You can request a beta build [on our Discord community](https://discord.gg/y5vwgXkz2f).

**Comment by unobatbayar** [comment]
@olokobayusuf thank you!
