### ISSUE TITLE
The more it is repeated, the lower the video fps.

### ISSUE THREAD

**Issue by isyoon0721** [natsuite/NatCorder-Performance-Extensions#17]
Unity 2020.3.21f1
NatCoder 1.8.1
Perfomance Extensions 0.0.3
ARFoundation in project
Model: Samsung S21 Ultra

The more I shoot repeatedly, the lower the fps of the recorded video.
21fps , 15fps , 10fps...
Even at the beginning, it is not possible to shoot at 30fps.

C# Code
    public void StartRecording()
    {        
        RecordingPath = "NONE";
        RecordingFinish = false;
                
        var sampleRate = AudioSettings.outputSampleRate;
        var channelCount = (int)AudioSettings.speakerMode;
        clock = new RealtimeClock();
        float rate = 1.0f;
        int bitrate = (int)(Screen.width * Screen.height * 4 * rate);
        recorder = new MP4Recorder(Screen.width, Screen.height, 60, sampleRate, channelCount, bitrate);
                        
        if (Application.platform == RuntimePlatform.Android)      
        {
            glinput = new GLESTextureInput(recorder, true);
            cameraInput = new CameraInput(glinput, clock, mainCamera);
        }
        else
        {
            cameraInput = new CameraInput(recorder, clock, mainCamera);
        }
        audioInput = new AudioInput(recorder, clock, audioListener);
    }

    public async void StopRecording()
    {       
        audioInput.Dispose();
        cameraInput.Dispose();
        
        RecordingPath = await recorder.FinishWriting();
        
        recorder = null;
        clock = null;                
    }

Profiler
![image](https://user-images.githubusercontent.com/53856289/147895125-202b30aa-57d5-4bbe-8574-5b4a7404d718.png)

**Comment by olokobayusuf** [comment]
You probably want to reduce your recording resolution. `Screen.width`x`Screen.height` is pretty high.

**Comment by isyoon0721** [comment]
Thank you for answer.

I have additional questions to ask.

Why is my draw call increasing from 26 to 45 while recording?
It seems to re-render everything except the UI.
Isn't it enough to just copy the final Rendertexture of the Main Camera?

**Comment by olokobayusuf** [comment]
> Why is my draw call increasing from 26 to 45 while recording?
> It seems to re-render everything except the UI.
> Isn't it enough to just copy the final Rendertexture of the Main Camera?

This is correct. *NatCorder is not a screen recorder*, so it's infeasible to copy "the final RenderTexture" (sometimes, there's no such concept) of the main camera. Recording multiple game cameras; recording only some game cameras; and recording with a resolution that doesn't exactly match the screen resolution are only some of the scenarios where it's impossible to do what you describe.

That being said, if your setup allows you to simply copy what the main camera sees, you can always write your own `CameraInput` implementation that does what you've described.
