### ISSUE TITLE
Recording on Android result in first frame black

### ISSUE THREAD

**Issue by Nolkeg** [natsuite/NatCorder-Performance-Extensions#2]
Video example
[https://streamable.com/v5uydz](url)

My set up
Unity 2020.3.4 LTS
Natcorder 1.8
Natdevice 1.0.2
NCPX

This problem seems to be caused by ncpx, since it won't occur when I remove ncpx from the project.

code for recording
![image](https://user-images.githubusercontent.com/46750330/115489336-3e54e300-a286-11eb-9c61-30e376f0d263.png)

**Comment by olokobayusuf** [comment]
Thanks for reporting this @Nolkeg , I'll check it out today or tomorrow.

**Comment by olokobayusuf** [comment]
Hey @Nolkeg , I have not been able to reproduce this issue on my S7 or S21.  Can you confirm that your app is running with OpenGL ES? You should not use `GLESTextureInput` if your app renders with Vulkan.
