### ISSUE TITLE
Multiple errors on adding

### ISSUE THREAD

**Issue by creativewax** [natsuite/NatCorder-Performance-Extensions#9]
Library/PackageCache/com.natsuite.ncpx@c9b2ef2a55/Runtime/Inputs/MTLTextureInput.cs(65,34): error CS0539: 'MTLTextureInput.frameSize' in explicit interface declaration is not found among members of the interface that can be implemented

Library/PackageCache/com.natsuite.ncpx@c9b2ef2a55/Runtime/Inputs/WatermarkTextureInput.cs(94,34): error CS0539: 'WatermarkTextureInput.frameSize' in explicit interface declaration is not found among members of the interface that can be implemented

Library/PackageCache/com.natsuite.ncpx@c9b2ef2a55/Runtime/Inputs/GLESTextureInput.cs(65,34): error CS0539: 'GLESTextureInput.frameSize' in explicit interface declaration is not found among members of the interface that can be implemented

Library/PackageCache/com.natsuite.ncpx@c9b2ef2a55/Runtime/Inputs/CropTextureInput.cs(67,34): error CS0539: 'CropTextureInput.frameSize' in explicit interface declaration is not found among members of the interface that can be implemented

**Comment by olokobayusuf** [comment]
Hey @creativewax , you'll need to upgrade to NatCorder 1.8.1 on the Asset Store.
